[about]
name = "LoserKugua"
avatar = "loserkugua.jpg"
hobbies = ["programming", "gaming(?)", "reading"]
skills = ["Qt", "Python"]

[social]
github = "LoserKugua"
website = "https://www.cnblogs.com/woshilaji"
