[about]
name = "TrailblazerWu"
avatar = "TrailblazerWu.jpg"
hobbies = ["Sleeping", "Programming", "Games","Reading"]
skills = ["C#","Python"]

[social]
github = "brzgw555"
website = "https://brzgw555.github.io/"
