[about]
name = "于้้้้้้้้้้้้้้้้้้้้博涵้้้้้้้้้้้้้้้้้้้้"
avatar = "ybh1998.jpeg"
hobbies = ["🎮Gaming", "🏖️Travelling", "🫕BBQ"]
skills = ["Rust", "OpenCL", "FPGA"]

[social]
github = "ybh1998"
website = "https://www.ybh1998.space/"

